### ISSUE TITLE
Does not auto-merge multiple dependency updates

### ISSUE THREAD

**Issue by SparrowBrain** [koj-co/dependabot-pr-action#54]
### Description
`dependabot-pr-action` does not merge [Pull Requests](https://github.com/SparrowBrain/GOG-Galaxy-Suggester/pull/19) for multiple dependency updates.
![image](https://user-images.githubusercontent.com/17652035/111896583-651fbf80-8a23-11eb-97f3-98eea390e4bb.png)

The workflow file:
```
name: Auto-merge
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  test:
    name: Auto-merge
    runs-on: ubuntu-latest
    steps:
      - uses: koj-co/dependabot-pr-action@master
        with:
          token: ${{ secrets.AUTO_MERGE_TOKEN }}
          merge: true
```

## Expected behaviour
Since the configuration is set to `merge: true`, it is expected that after the checks succeed the Pull Request would be merged.

## Actual behaviour
`dependabot-pr-action` fails to parse the version numbers from the Pull Request title and [skips the Pull Request](https://github.com/SparrowBrain/GOG-Galaxy-Suggester/runs/2158537492?check_suite_focus=true).
```
Starting PR 19
All status checks true true
Bump react and react-dom
Diff version is 
Starting PR 4
```
